module.exports =  {
    cardFiles: [ // each image resource is loaded into an array and elements can request them by either index or name
        {src: require(`../../images/cards/card_back.png`), name: 'card_back'},
        {src: require(`../../images/cards/empty.png`), name: 'card_empty'},
        {src: require(`../../images/cards/invisible.png`), name: 'invisible'},
        {src: require(`../../images/cards/A_S.png`), name: 'A_S'},
        {src: require(`../../images/cards/2_S.png`), name: '2_S'},
        {src: require(`../../images/cards/3_S.png`), name: '3_S'},
        {src: require(`../../images/cards/4_S.png`), name: '4_S'},
        {src: require(`../../images/cards/5_S.png`), name: '5_S'},
        {src: require(`../../images/cards/6_S.png`), name: '6_S'},
        {src: require(`../../images/cards/7_S.png`), name: '7_S'},
        {src: require(`../../images/cards/8_S.png`), name: '8_S'},
        {src: require(`../../images/cards/9_S.png`), name: '9_S'},
        {src: require(`../../images/cards/10_S.png`), name: '10_S'},
        {src: require(`../../images/cards/J_S.png`), name: 'J_S'},
        {src: require(`../../images/cards/Q_S.png`), name: 'Q_S'},
        {src: require(`../../images/cards/K_S.png`), name: 'K_S'},
        
        {src: require(`../../images/cards/A_C.png`), name: 'A_C'},
        {src: require(`../../images/cards/2_C.png`), name: '2_C'},
        {src: require(`../../images/cards/3_C.png`), name: '3_C'},
        {src: require(`../../images/cards/4_C.png`), name: '4_C'},
        {src: require(`../../images/cards/5_C.png`), name: '5_C'},
        {src: require(`../../images/cards/6_C.png`), name: '6_C'},
        {src: require(`../../images/cards/7_C.png`), name: '7_C'},
        {src: require(`../../images/cards/8_C.png`), name: '8_C'},
        {src: require(`../../images/cards/9_C.png`), name: '9_C'},
        {src: require(`../../images/cards/10_C.png`), name: '10_C'},
        {src: require(`../../images/cards/J_C.png`), name: 'J_C'},
        {src: require(`../../images/cards/Q_C.png`), name: 'Q_C'},
        {src: require(`../../images/cards/K_C.png`), name: 'K_C'},

        {src: require(`../../images/cards/A_H.png`), name: 'A_H'},
        {src: require(`../../images/cards/2_H.png`), name: '2_H'},
        {src: require(`../../images/cards/3_H.png`), name: '3_H'},
        {src: require(`../../images/cards/4_H.png`), name: '4_H'},
        {src: require(`../../images/cards/5_H.png`), name: '5_H'},
        {src: require(`../../images/cards/6_H.png`), name: '6_H'},
        {src: require(`../../images/cards/7_H.png`), name: '7_H'},
        {src: require(`../../images/cards/8_H.png`), name: '8_H'},
        {src: require(`../../images/cards/9_H.png`), name: '9_H'},
        {src: require(`../../images/cards/10_H.png`), name: '10_H'},
        {src: require(`../../images/cards/J_H.png`), name: 'J_H'},
        {src: require(`../../images/cards/Q_H.png`), name: 'Q_H'},
        {src: require(`../../images/cards/K_H.png`), name: 'K_H'},

        {src: require(`../../images/cards/A_D.png`), name: 'A_D'},
        {src: require(`../../images/cards/2_D.png`), name: '2_D'},
        {src: require(`../../images/cards/3_D.png`), name: '3_D'},
        {src: require(`../../images/cards/4_D.png`), name: '4_D'},
        {src: require(`../../images/cards/5_D.png`), name: '5_D'},
        {src: require(`../../images/cards/6_D.png`), name: '6_D'},
        {src: require(`../../images/cards/7_D.png`), name: '7_D'},
        {src: require(`../../images/cards/8_D.png`), name: '8_D'},
        {src: require(`../../images/cards/9_D.png`), name: '9_D'},
        {src: require(`../../images/cards/10_D.png`), name: '10_D'},
        {src: require(`../../images/cards/J_D.png`), name: 'J_D'},
        {src: require(`../../images/cards/Q_D.png`), name: 'Q_D'},
        {src: require(`../../images/cards/K_D.png`), name: 'K_D'},
    ]
};